Update gatsby.yml

diff --git a/.github/workflows/gatsby.yml b/.github/workflows/gatsby.yml
--- a/.github/workflows/gatsby.yml
+++ b/.github/workflows/gatsby.yml
@@ -3,6 +3,7 @@ name: Deploy Gatsby site to Pages
 on:
   push:
     branches: ["master"]
+
   workflow_dispatch:
 
 permissions:
@@ -24,20 +25,32 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
           node-version: "18"
-          cache: "npm"
-
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
       - name: Setup Pages
         id: pages
         uses: actions/configure-pages@v4
         with:
           static_site_generator: gatsby
-
-      - name: Restore Gatsby cache
+      - name: Restore cache
         uses: actions/cache@v4
         with:
           path: |
@@ -46,20 +59,21 @@ jobs:
           key: ${{ runner.os }}-gatsby-build-${{ hashFiles('public') }}
           restore-keys: |
             ${{ runner.os }}-gatsby-build-
-
       - name: Install dependencies
-        run: npm ci
-
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
       - name: Build with Gatsby
         env:
-          PREFIX_PATHS: "true"
-          NODE_OPTIONS: "--max-old-space-size=4096"
-        run: npm run build
-
+          PREFIX_PATHS: 'true'
+          NODE_TLS_REJECT_UNAUTHORIZED: 0
+        run: ${{ steps.detect-package-manager.outputs.runner }} gatsby build
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
           path: ./public
+      - name: Increase memory limit and run build
+        run: |
+          export NODE_OPTIONS="--max-old-space-size=4096"
+          yarn run build
 
   deploy:
     environment:
